name: '[M] Create Release Candidate Branch'
on:
  workflow_dispatch:
jobs:
  #Uses https://github.com/marketplace/actions/create-branch
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: development
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-T%H.%M.%S')"
      - name: Create release branch name
        id: branch
        run: echo "::set-output name=name::$(echo release-candidate-UTC-${{ steps.date.outputs.date }})"
      - name: Make release branch
        run: |
          git checkout -b ${{ steps.branch.outputs.name }}
          git push -u origin ${{ steps.branch.outputs.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Remove preexisting release notes for branch if exists
        run: |
          if [ -f ${{ steps.branch.outputs.name }} ] ; then
            rm .releases/${{ steps.branch.outputs.name }}-notes.txt
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      - name: Create file
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME = ".releases/${{ steps.branch.outputs.name }}-notes.txt"
          FILE_DATA = "#Example file\nThis is an example"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 