name: '[M] Create Release Candidate Branch'
on:
  workflow_dispatch:
jobs:
  #Uses https://github.com/marketplace/actions/create-branch
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: development
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-T%H.%M.%S')"
      - name: Make release branch
        run: |
          git checkout -b release-candidate-${{ steps.date.outputs.date }}
          git push -u origin release-candidate-${{ steps.date.outputs.date }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}