name: Auto Assign Issues and PRs to Main Org Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.2.4
        with:
          project: 'https://github.com/orgs/Cassio-is-Great/projects/5'
          column: 'To Do'
          repo-token: ${{ secrets.AUTOMATE_ISSUES_PULL_REQUESTS }}